# Build for the 2002 sources.
#
# The original build was a Dev-C++ project file (original/mapColoring.dev) with
# absolute paths into D:\Projects\mapColoring and an icon resource, so it built
# on exactly one machine. This replaces it: objects under build/, header
# dependencies generated by the compiler, and every variable below overridable
# from the command line.
#
#   make                 build ./mapColoring
#   make test            build, then check the four graphs against tests/expected
#   make install         install into $(DESTDIR)$(PREFIX)/bin
#   make graphs          render maps/*.dot and maps/*.gif (needs perl, Graphviz)
#   make clean           remove build/ and the binary
#   make CC=gcc OPT=-O0  any of the variables, from the command line

CC       ?= cc
CSTD     ?= -std=c99
WARNINGS ?= -Wall -Wextra -Wstrict-prototypes
OPT      ?= -O2
CFLAGS   ?= $(CSTD) $(WARNINGS) $(OPT)
LDLIBS   ?= -lm

PREFIX  ?= /usr/local
BINDIR  ?= $(PREFIX)/bin
DESTDIR ?=

BIN     := mapColoring
SRCDIR  := src
OBJDIR  := build
SOURCES := $(wildcard $(SRCDIR)/*.c)
OBJECTS := $(SOURCES:$(SRCDIR)/%.c=$(OBJDIR)/%.o)
DEPS    := $(OBJECTS:.o=.d)

.PHONY: all test install uninstall graphs clean distclean help
.DEFAULT_GOAL := all

all: $(BIN)

$(BIN): $(OBJECTS)
	$(CC) $(LDFLAGS) -o $@ $(OBJECTS) $(LDLIBS)

# -MMD -MP writes build/<name>.d beside each object, so touching a header
# rebuilds what includes it. Understood by both gcc and clang.
$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -c -o $@ $<

$(OBJDIR):
	mkdir -p $(OBJDIR)

test: $(BIN)
	./tests/run.sh ./$(BIN)

install: $(BIN)
	install -d $(DESTDIR)$(BINDIR)
	install -m 755 $(BIN) $(DESTDIR)$(BINDIR)/$(BIN)

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/$(BIN)

# maps/Makefile is the one that shipped with the 2004 binary release and is left
# as it was written, including a clean target that says `rm -f maps/*.gif` from
# inside maps/ and so deletes nothing. The sweep is in distclean here.
graphs:
	$(MAKE) -C maps graphs

clean:
	rm -rf $(OBJDIR) $(BIN)

distclean: clean
	rm -f maps/*.dot maps/*.gif

help:
	@echo 'Targets: all test install uninstall graphs clean distclean'
	@echo 'Variables: CC CFLAGS CSTD WARNINGS OPT LDFLAGS LDLIBS PREFIX BINDIR DESTDIR'

-include $(DEPS)
